name: dedsi-native-release

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore ./DedsiNative.Template.csproj

      - name: Build
        run: dotnet build --no-restore ./DedsiNative.Template.csproj

      - name: Pack NuGet package
        run: dotnet pack -c Release -o "./" ./DedsiNative.Template.csproj

      - name: Publish NuGet package
        run: dotnet nuget push '*.nupkg' -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
